name: periodic test
on:
  schedule:
    # NZST = UTC + 12
    # Schedule to run at midnight & lunch-time
    - cron: '0 0,12 * * *'
jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-platform: ["arduino:sam", "SparkFun:samd"]
        include:
          - arduino-platform: "arduino:sam"
            fqbn: "arduino:sam:arduino_due_x"
          - arduino-platform: "SparkFun:samd"
            fqbn: "SparkFun:samd:samd21_dev"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          ./build.sh ${{ matrix.arduino-platform }} ${{ matrix.fqbn }}
