name: test
on: [push, pull_request]
jobs:
  test-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-platform: ["arduino:sam", "SparkFun:samd"]
        include:
          - arduino-platform: "arduino:sam"
            fqbn: "arduino:sam:arduino_due_x"
          - arduino-platform: "SparkFun:samd"
            fqbn: "SparkFun:samd:samd21_dev"
    steps:
      - uses: actions/checkout@v3
      - run: |
          ./build.sh ${{ matrix.arduino-platform }} ${{ matrix.fqbn }}
